CREATE DATABASE av3bancodedados;

CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  password VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS admins (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id INT,

  FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS teachers (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id INT,

  FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS coordinators (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id INT,

  FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS courses (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  coordinator_id INT,

  FOREIGN KEY(coordinator_id) REFERENCES coordinators(id)
);

CREATE TABLE IF NOT EXISTS subjects (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS course_subjects (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  course_id INT,
  subject_id INT,

  FOREIGN KEY (course_id) REFERENCES courses(id),
  FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

CREATE TABLE IF NOT EXISTS classes (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  teacher_id INT,
  subject_id INT,

  FOREIGN KEY (subject_id) REFERENCES subjects(id),
  FOREIGN KEY (teacher_id) REFERENCES teachers(id)
);

CREATE TABLE IF NOT EXISTS students (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  class_id INT,

  FOREIGN KEY (class_id) REFERENCES classes(id)
);